# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Calendrier de l'Avent Open Data 2017
email: info@data.gouv.fr
description: >-
  Pas de data, pas de chocolat !
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  etalab


# So as we can reuse the same website for each year
permalink: /:year/:day

# Disable when tests are over
future: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

calendar:
  days_order:
    - 2017-12-08
    - 2017-12-04
    - 2017-12-20
    - 2017-12-01
    - 2017-12-19
    - 2017-12-21
    - 2017-12-11
    - 2017-12-02
    - 2017-12-18
    - 2017-12-22
    - 2017-12-07
    - 2017-12-10
    - 2017-12-23
    - 2017-12-09
    - 2017-12-05
    - 2017-12-14
    - 2017-12-16
    - 2017-12-13
    - 2017-12-03
    - 2017-12-17
    - 2017-12-24
    - 2017-12-15
    - 2017-12-12
    - 2017-12-06

piwik:
  site_id: xx
  site_domains:
    - "etalab.github.io/calendrier-lavent"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
