# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Calendrier de l'Avent Open Data 2017
email: info@data.gouv.fr
description: >-
  Pas de data, pas de chocolat !
baseurl: "/"
url: "https://avent.data.gouv.fr"
twitter_username: datagouvfr
github_username:  etalab

# Disable when OK with content
future: true


# So as we can reuse the same website for each year
permalink: /:year/:day

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

calendar:
  days_order:
    - 2017-12-08T00:00:00
    - 2017-12-04T00:00:00
    - 2017-12-20T00:00:00
    - 2017-12-01T00:00:00
    - 2017-12-19T00:00:00
    - 2017-12-21T00:00:00
    - 2017-12-11T00:00:00
    - 2017-12-02T00:00:00
    - 2017-12-18T00:00:00
    - 2017-12-22T00:00:00
    - 2017-12-07T00:00:00
    - 2017-12-10T00:00:00
    - 2017-12-23T00:00:00
    - 2017-12-09T00:00:00
    - 2017-12-05T00:00:00
    - 2017-12-14T00:00:00
    - 2017-12-16T00:00:00
    - 2017-12-13T00:00:00
    - 2017-12-03T00:00:00
    - 2017-12-17T00:00:00
    - 2017-12-24T00:00:00
    - 2017-12-15T00:00:00
    - 2017-12-12T00:00:00
    - 2017-12-06T00:00:00

piwik:
  site_id: xx
  site_domains:
    - "avent.data.gouv.fr/calendrier-lavent"

exclude:
  - README.md
  - circle.yml
  - deploy
  - vendor/bundle/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
