backend:
  name: github
  base_url: https://api.staticweb-01.etalab.gouv.fr
  site_domain: avent.data.gouv.fr/
  repo: etalab/calendrier-lavent

media_folder: "img/uploads"

collections:
  - name: "posts"
    label: "Article"
    folder: "_posts"
    create: true
    slug: "{{date}}-{{title}}"
    title: {{title}}
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date de publication de l'article", name: "date", widget: "string"}
      - {label: "Type", name: "type", widget: "string"}
      - {label: "Publieur", name: "publisher", widget: "string"}
      - {label: "URL", name: "url", widget: "string"}
      - {label: "Description", name: "body", widget: "markdown"}

